version: '2'

networks:
  LEMP:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: NGINX
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - LEMP

  mariaDB:
    image: mariadb:latest
    container_name: MYSQL
    volumes:
      - ./database:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    depends_on:
      - nginx
    environment:
      - MYSQL_ROOT_PASSWORD=654321
    networks:
      - LEMP

  php:
    image: php:7.4-fpm-alpine
    container_name: PHP
    volumes:
      - ./:/code
    ports:
      - "9100:9000"
    networks:
      - LEMP
    build:
      context: .
      dockerfile: Dockerfile

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PHPMYADMIN
    ports:
      - "8183:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mariaDB
    networks:
      - LEMP

